#!/usr/bin/env bash
#
declare PRIVKEY
PRIVKEY=${2:-}

help(){

    printf "Usage:\n"
    printf "gnostr-nip --sec <sha256_hash>\n"
    printf "gnostr-nip --sec $(gnostr-sha256 $$)\n"

}

nip0(){

BANNER=https://avatars.githubusercontent.com/u/135379339?s=400&u=e38855df24087feb9a6679c5e3974816e6aa3753&v=4
##echo $BANNER
PICTURE=https://avatars.githubusercontent.com/u/135379339?s=400&u=e38855df24087feb9a6679c5e3974816e6aa3753&v=4
echo $PICTURE
##
WEBSITE=gnostr.org
echo "$WEBSITE"
DAMUS_DONATION_V2=0
echo "$DAMUS_DONATION_V2"
LUD06=""
echo "$LUD06"
DISPLAY_NAME=$(gnostr-weeble)
echo "$DISPLAY_NAME"
ABOUT=$(gnostr-weeble)
echo "$ABOUT"
NAME=$(gnostr-weeble)
echo "$NAME"

#MESSAGE=message
MESSAGE={"content":"{\"website\":\"$WEBSITE\",\"lud06\":\"\",\"damus_donation\":0,\"picture\":\"https://avatars.githubusercontent.com/u/135379339?s=400&u=e38855df24087feb9a6679c5e3974816e6aa3753&v=4\",\"display_name\":\"0\",\"about\":\"0\",\"name\":\"0\"}","created_at":1706290679,"id":"12ab57b02dfd76dc01649510f4cccf624665b486cc6c20289dfdc9dc5713c8de","kind":0,"pubkey":"b8cc8217b24ad57f9ddc4ee31fd91da75af6f9353d8124ee292d5145fdd99d0f","sig":"a44e1e3aab3596b22905e91146d0110983029fafbf259211bde01a84c278b55507441c9c9f86b5857cb983adcb28ae42a2dca309b6b2ce8b5ae808a9250465af","tags":[]}
##MESSAGE=\
##"\{\"banner\":\"$BANNER\",\"website\":\"$WEBSITE\",\"damus_donation_v2\":$DAMUS_DONATION_V2,\"lud06\":\"$LUD06",\"picture\":\"$PICTURE\",\"display_name\":\"$DISPLAY_NAME\",\"about\":\"$ABOUT\",\"name\":\"$NAME\"\}"

#echo $MESSAGE

#exit;
gnostr --sec $PRIVKEY               \
  --kind 0                          \
  --tag gnostr gnostr               \
  --tag weeble $(gnostr-weeble)     \
  --tag wobble $(gnostr-wobble)     \
  --tag block $(gnostr-blockheight) \
  --content "$MESSAGE"
}

if [ ! -z "$1" ]; then
  if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    help
    if [ "$2" == "0" ]; then
    echo "NIP-0: metadata: the content is set to a stringified JSON object {name: <username>, about: <string>, picture: <url, string>} describing the user who created the event. A relay may delete older events once it gets a new one for the same pubkey.";
    fi
    if [ "$2" == "1" ]; then
      echo "NIP-1:"
    fi
    if [ "$2" == "2" ]; then
      echo "NIP-2:"
    fi
  fi
  if [ "$1" == "--sec" ]; then
    if [ "$2" == "" ]; then
      echo "provide a sha256 hash for private key"
    else
      PRIVKEY=$2
      echo "$PRIVKEY"
      nip0
    fi
  fi
exit
fi


# gnostr-query -i $(gnostr-nip0  | jq .[1] | tr -d "\"" ) | gnostr-cat -u wss://nos.lol
#
# gnostr-query -k 0 -l 1 | gnostr-cat -u wss://nos.lol | jq .[2].content | tr -d "\""
#
# echo $(./template/gnostr-nip0) #| gnostr-relays
#
# echo $(./template/gnostr-nip0) | gnostr-cat -u wss://nos.lol | jq .[1] | tr -d "\""
#
# echo $(gnostr-query -k 0 -l 1 | gnostr-cat -u wss://nos.lol | jq .[2].content | jq | tr -d "\"") | tr -d "\\"
#
# gnostr --sec $(gnostr-sha256) --envelope --content $(echo gnostr-query -k 0 -l 1 | gnostr-cat -u wss://nos.lol | jq .[2].content ) | tr -d "\\"
#
