#!/usr/bin/env bash

set -eo pipefail
gnostr-set-relays
which gnostr-cat >/dev/null || cargo install gnostr-cat || echo "install rustup"
NOSTR_RELAYER=${NOSTR_RELAYER:-gnostr-cat}

if ! command -v $NOSTR_RELAYER >&2 >/dev/null; then
	printf "error: nostr relayer '%s' not found, set \$NOSTR_RELAYER or install '%s'\n" $NOSTR_RELAYER $NOSTR_RELAYER
	exit 1
fi

check_cmd() {
	if ! command -v $1 >&2 >/dev/null; then
		printf "error: $1 is required. please install. \n"
		exit 0
	fi
}

check_cmd "gnostr"

usage() {
	printf "usage: gnostr-git-send [options...] <commit> [gnostr options...]\n\n"

	printf "OPTIONS\n\n"
	printf "     -r            Relay to broadcast to. Will use 'git config nostr.relays' by default\n"
	printf "     -d            Dry run. Just print event to stdout instead of relaying.\n"
	printf "\n"
	printf "     any other gnostr option is supported here:\n\n"
	printf "GNOSTR OPTIONS\n"
	gnostr | sed '1,/OPTIONS/d'
	printf "\nEXAMPLES\n\n"
	printf "gnostr-git-send -d HEAD^- -t gnostr -t gnostr-git-send --pow 15\n\n"
	exit 0
}
version() {
	printf "v0.0.0"
}

while getopts "dr:t:" o; do
    case "${o}" in
        h)
            usage
            ;;
        help)
            usage
            ;;
        v)
            version
            ;;
        r)
            relay=${OPTARG}
            ;;
        t)
            tag=${OPTARG}
            ;;
        d)
            dryrun=1
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))


if [ -z $relay ]; then
  relay=$(git config gnostr.relays) || relay=$(gnostr-git config gnostr.relays);
	if [[ $relay == "" ]]; then
		unset relay
	fi
fi

if [ -z $1 ]; then
	usage
	exit 0
fi

commit=$1
shift

# this can be overridden
sec="$(git config nostr.secretkey || :)"
if [[ $sec != "" ]]; then
	sec="--sec $sec"
fi

hashtag=$(git config nostr.hashtag || :)
if [[ $hashtag != "" ]]; then
	hashtag="--tag t $hashtag"
fi

patch="$(git format-patch --stdout $commit)"
subject=$(<<<"$patch" grep "^Subject:"| head -n1 | sed 's,^Subject: ,,')
author=$(<<<"$patch" grep "^From:"| head -n1 | sed 's,^From: ,,')
json=$(gnostr --envelope $sec --kind 19691228 $hashtag --tag author "$author" --tag subject "$subject" --content "$patch" "$@")

id=$(jq -r '.[1].id' <<<"$json")

if [ -n "$dryrun" ]; then
	echo "$json"
	printf "\nDRY RUN. printing event data\n" >&2
elif [ -z "$relay" ]; then
	echo "$json"
	printf "\nRELAY NOT SET, not relaying. Use -r wss://relay.damus.io or 'git config --global nostr.relays wss://relay.damus.io'\n" >&2
else
	echo "$id"
	printf "relaying to $relay using $NOSTR_RELAYER...\n" >&2
	<<<$json $NOSTR_RELAYER $relay
fi

if [[ $sec == "" ]]; then
	printf "NOSTR SECRET KEY NOT SET, using random key. Use --sec <key> or 'git config --global nostr.secretkey <hexkey>'\n" >&2
fi
