#!/usr/bin/env bash

ARG=${1:-}

help(){

  printf "usage:\n"
  printf "	 gnostr-proxy-relay-list\n"
  printf "	 gnostr-proxy-relay-list -h --help help\n"
  printf "	 gnostr-proxy-relay-list -v --version version\n"
  printf "	 gnostr-proxy-relay-list -t --tag tag tags\n"

  printf "logging:\n"
  printf "	tail -f /tmp/gnostr-proxy.log\n"
  exit;
}
if [[ $ARG == "-h" ]];
then
	help;exit
fi
if [[ $ARG == "--help" ]];
then
	help;exit
fi
if [[ $ARG == "help" ]];
then
	help;exit
fi
if [[ $ARG == "-v" ]];
then
  printf "v0.0.0"; exit
fi
if [[ $ARG == "--version" ]];
then
  printf "v0.0.0"; exit
fi

RELAYS=$(curl -sS --get http://localhost:6102 | sed 's/<[^>]*>//g' | sed '/^$/d')
#echo $RELAYS
for relay in $RELAYS;
do
if [[ $ARG == "-t" ]] ||[[ $ARG == "--tag" ]] || [[ $ARG == "tag" ]] ||[[ $ARG == "tags" ]];
then
echo  "--tag r $relay"
else
  echo $relay
fi
done
