#!/usr/bin/env bash
#
#
GNOSTR=$(which gnostr)
#export GNOSTR
#echo $GNOSTR

declare PRIVKEY
PRIVKEY=${2:-'0000000000000000000000000000000000000000000000000000000000000000'}

echo $2
echo '$2'
echo "$2"
## exit
## PUBKEY for 0000000000000000000000000000000000000000000000000000000000000001
## 79be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798


## TESTS=$(echo {0000000000000000000000000000000000000000000000000000000000000001..0000000000000000000000000000000000000000000000000000000000001000})
## for ms in $TESTS
## do
##     echo $ms 2>/dev/null
## done
## exit

test_zero(){
  echo "test_zero()";
  echo "expect:"
  echo "could not hex decode secret key"
  $GNOSTR --sec $PRIVKEY;
  $GNOSTR --sec '$PRIVKEY';
  $GNOSTR --sec "$PRIVKEY";
  exit;
}
test_one(){
  echo "test_one()";
  TESTS=$(echo {0000000000000000000000000000000000000000000000000000000000000001..0000000000000000000000000000000000000000000000000000000000001000})
  for ms in $TESTS
  do
    echo $ms 2>/dev/null
    $GNOSTR --sec $ms -t gnostr -t $(gnostr-weeble) -t $(gnostr-blockheight) -t $(gnostr-wobble) --content "$(gnostr-weeble)/$(gnostr-blockheight)/$(gnostr-wobble))" --pow 1 | $(which gnostr-post-event);
    #$GNOSTR --sec '$PRIVKEY';##this will fail
    #$GNOSTR --sec "$TESTS";
  done
  exit

  $GNOSTR --sec $PRIVKEY;
  #$GNOSTR --sec '$PRIVKEY';##this will fail
  $GNOSTR --sec "$PRIVKEY";
  exit;
}

if \
  [[ \
  $2 \
  == \
  "0000000000000000000000000000000000000000000000000000000000000000" \
  ]];
then
  test_zero;
  exit;
fi
if \
  [[ \
  $2 \
  == \
  "0000000000000000000000000000000000000000000000000000000000000001" \
  ]];
then
  test_one;
  exit;
fi


test_zero(){
  echo "test_zero()";
  $GNOSTR --sec $2;
  exit;
}
test_one(){
  echo "test_one()";
  $GNOSTR --sec $2;
  exit;
}

help(){

    printf "Usage:\n"
    printf "gnostr-nip --sec <sha256_hash>\n"
    printf "gnostr-nip --sec $(gnostr-sha256 $$)\n"
    printf "\n"
    printf "Test triggers:\n"
    printf "gnostr-nip --sec \"0000000000000000000000000000000000000000000000000000000000000000\""
    printf "gnostr-nip --sec \"0000000000000000000000000000000000000000000000000000000000000001\""

}

nip0(){

BANNER="https://avatars.githubusercontent.com/u/135379339?s=400&u=e38855df24087feb9a6679c5e3974816e6aa3753&v=4"
#echo $BANNER
PICTURE="https://avatars.githubusercontent.com/u/135379339?s=400&u=e38855df24087feb9a6679c5e3974816e6aa3753&v=4"
#echo $PICTURE
##exit;
##
WEBSITE=gnostr.org
#echo "$WEBSITE"
DAMUS_DONATION_V2=0
#echo "$DAMUS_DONATION_V2"
LUD06=""
#echo "$LUD06"
DISPLAY_NAME=$(gnostr-weeble)
#echo "$DISPLAY_NAME"
ABOUT_ME="#gnostr/$(gnostr-weeble)"
#echo "$ABOUT"
NAME=$(gnostr-weeble)
#echo "$NAME"

CREATED_AT=$(date +%s)
#echo $CREATED_AT

MESSAGE="{\"banner\":\"$BANNER\",\"website\":\"$WEBSITE\",\"lud06\":\"$LUD06\",\"nip05\":\"$NIP_05\",\"picture\":\"https://avatars.githubusercontent.com/u/135379339?s=400&u=e38855df24087feb9a6679c5e3974816e6aa3753&v=4\",\"display_name\":\"$DISPLAY_NAME\",\"about\":\"$ABOUT_ME\",\"name\":\"$NAME\"}"

$GNOSTR --sec $PRIVKEY              \
  --kind 0                          \
  -t gnostr                         \
  --tag gnostr gnostr               \
  --tag weeble $(gnostr-weeble)     \
  --tag wobble $(gnostr-wobble)     \
  --tag block $(gnostr-blockheight) \
  --content "$MESSAGE"
}

if [ ! -z "$1" ]; then
  if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    help
    if [ "$2" == "0" ]; then
    echo "NIP-0: metadata: the content is set to a stringified JSON object {name: <username>, about: <string>, picture: <url, string>} describing the user who created the event. A relay may delete older events once it gets a new one for the same pubkey.";
    fi
    if [ "$2" == "1" ]; then
      echo "NIP-1:"
    fi
    if [ "$2" == "2" ]; then
      echo "NIP-2:"
    fi
  fi
  if [ "$1" == "--sec" ]; then
    if [ "$2" == "" ]; then
      echo "provide a sha256 hash for private key"
    else
      PRIVKEY=$2
      mkdir -p ~/.gnostr
      #touch ~/.gnostr/$PRIVKEY
      nip0
    fi
  fi
exit
fi


# gnostr-query -i $(gnostr-nip0  | jq .[1] | tr -d "\"" ) | gnostr-cat -u wss://nos.lol
#
# gnostr-query -k 0 -l 1 | gnostr-cat -u wss://nos.lol | jq .[2].content | tr -d "\""
#
# echo $(./template/gnostr-nip0) #| gnostr-relays
#
# echo $(./template/gnostr-nip0) | gnostr-cat -u wss://nos.lol | jq .[1] | tr -d "\""
#
# echo $(gnostr-query -k 0 -l 1 | gnostr-cat -u wss://nos.lol | jq .[2].content | jq | tr -d "\"") | tr -d "\\"
#
# gnostr --sec $(gnostr-sha256) --envelope --content $(echo gnostr-query -k 0 -l 1 | gnostr-cat -u wss://nos.lol | jq .[2].content ) | tr -d "\\"
#
