#!/usr/bin/env bash

if [[ $1 = "-h" ]] || [[ $1 = "--help" ]]; then

  echo ""help""

exit;
fi
if [[ $1 = "-v" ]] || [[ $1 = "--version" ]]; then

  echo ""v0.0.2""

exit;
fi


gnostr-web --http-address=0.0.0.0 --http-port=80 --deploy-path=/web --docroot=. & \
  $(shell which open) http://0.0.0.0:80¬
